// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace kurs.Migrations
{
    [DbContext(typeof(Library))]
    [Migration("20240527100855_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("AssignedTag", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("descriptiontitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("descriptiontitleId");

                    b.HasIndex("tagName");

                    b.ToTable("assignedTags");
                });

            modelBuilder.Entity("AssignedTagR", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("descriptiontitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("descriptiontitleId");

                    b.HasIndex("tagName");

                    b.ToTable("assignedTagsR");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<long>("order")
                        .HasColumnType("INTEGER");

                    b.Property<long>("removedTypeAm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("removedTypeAm");

                    b.Property<long>("typeAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("name");

                    b.HasIndex("order")
                        .IsUnique();

                    b.ToTable("categorys");
                });

            modelBuilder.Entity("CategoryR", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<long>("order")
                        .HasColumnType("INTEGER");

                    b.Property<long>("removedTypeAm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("removedTypeAm");

                    b.Property<long>("typeAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("name");

                    b.HasIndex("order")
                        .IsUnique();

                    b.ToTable("categorysR");
                });

            modelBuilder.Entity("Description", b =>
                {
                    b.Property<long>("titleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("desk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("photoAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("titleId");

                    b.ToTable("descriptions");
                });

            modelBuilder.Entity("DescriptionR", b =>
                {
                    b.Property<long>("titleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("desk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("photoAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("titleId");

                    b.ToTable("descriptionsR");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("typeNavname")
                        .HasColumnType("TEXT");

                    b.HasKey("name");

                    b.HasIndex("typeNavname");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("TagR", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("typeNavname")
                        .HasColumnType("TEXT");

                    b.HasKey("name");

                    b.HasIndex("typeNavname");

                    b.ToTable("tagsR");
                });

            modelBuilder.Entity("Title", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("[id] || \"-t.webp\"", true);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.Property<string>("typename")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.HasIndex("typename");

                    b.ToTable("titles");
                });

            modelBuilder.Entity("TitleR", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("[id] || \"-t.webp\"", true);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.Property<string>("typename")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.HasIndex("typename");

                    b.ToTable("titlesR");
                });

            modelBuilder.Entity("Type", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("categoryName")
                        .HasColumnType("TEXT");

                    b.Property<long>("order")
                        .HasColumnType("INTEGER");

                    b.Property<long>("titleAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("name");

                    b.HasIndex("categoryName");

                    b.HasIndex("order")
                        .IsUnique();

                    b.ToTable("types");
                });

            modelBuilder.Entity("TypeR", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("categoryName")
                        .HasColumnType("TEXT");

                    b.Property<long>("order")
                        .HasColumnType("INTEGER");

                    b.Property<long>("titleAm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("name");

                    b.HasIndex("categoryName");

                    b.HasIndex("order")
                        .IsUnique();

                    b.ToTable("typesR");
                });

            modelBuilder.Entity("AssignedTag", b =>
                {
                    b.HasOne("Description", "description")
                        .WithMany("assignedlist")
                        .HasForeignKey("descriptiontitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tag", "tagNav")
                        .WithMany("assignedList")
                        .HasForeignKey("tagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("description");

                    b.Navigation("tagNav");
                });

            modelBuilder.Entity("AssignedTagR", b =>
                {
                    b.HasOne("DescriptionR", "description")
                        .WithMany("assignedlist")
                        .HasForeignKey("descriptiontitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TagR", "tagNav")
                        .WithMany("assignedList")
                        .HasForeignKey("tagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("description");

                    b.Navigation("tagNav");
                });

            modelBuilder.Entity("Description", b =>
                {
                    b.HasOne("Title", "title")
                        .WithOne("description")
                        .HasForeignKey("Description", "titleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("title");
                });

            modelBuilder.Entity("DescriptionR", b =>
                {
                    b.HasOne("TitleR", "title")
                        .WithOne("description")
                        .HasForeignKey("DescriptionR", "titleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("title");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.HasOne("Type", "typeNav")
                        .WithMany("taglist")
                        .HasForeignKey("typeNavname");

                    b.Navigation("typeNav");
                });

            modelBuilder.Entity("TagR", b =>
                {
                    b.HasOne("TypeR", "typeNav")
                        .WithMany("taglist")
                        .HasForeignKey("typeNavname");

                    b.Navigation("typeNav");
                });

            modelBuilder.Entity("Title", b =>
                {
                    b.HasOne("Type", "type")
                        .WithMany("titlelist")
                        .HasForeignKey("typename")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("type");
                });

            modelBuilder.Entity("TitleR", b =>
                {
                    b.HasOne("TypeR", "type")
                        .WithMany("titlelist")
                        .HasForeignKey("typename")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("type");
                });

            modelBuilder.Entity("Type", b =>
                {
                    b.HasOne("Category", "categoryNav")
                        .WithMany("typelist")
                        .HasForeignKey("categoryName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("categoryNav");
                });

            modelBuilder.Entity("TypeR", b =>
                {
                    b.HasOne("CategoryR", "categoryNav")
                        .WithMany("typelist")
                        .HasForeignKey("categoryName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("categoryNav");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("typelist");
                });

            modelBuilder.Entity("CategoryR", b =>
                {
                    b.Navigation("typelist");
                });

            modelBuilder.Entity("Description", b =>
                {
                    b.Navigation("assignedlist");
                });

            modelBuilder.Entity("DescriptionR", b =>
                {
                    b.Navigation("assignedlist");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Navigation("assignedList");
                });

            modelBuilder.Entity("TagR", b =>
                {
                    b.Navigation("assignedList");
                });

            modelBuilder.Entity("Title", b =>
                {
                    b.Navigation("description")
                        .IsRequired();
                });

            modelBuilder.Entity("TitleR", b =>
                {
                    b.Navigation("description");
                });

            modelBuilder.Entity("Type", b =>
                {
                    b.Navigation("taglist");

                    b.Navigation("titlelist");
                });

            modelBuilder.Entity("TypeR", b =>
                {
                    b.Navigation("taglist");

                    b.Navigation("titlelist");
                });
#pragma warning restore 612, 618
        }
    }
}
